project:
  type: website

website:
  title: "GISProject"
  navbar:
    left: 
      - href: proposal.qmd
        text: Proposal
  #    - href: method.qmd
  #      text: methodology
   #   - href: results.qmd
   #     text: results
    right:
      - href: index.qmd
        text: Home
    #  - href: about.qmd
format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual

