project:
  type: website

website:
  title: "GISProject"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: proposal.qmd
        text: Proposal
      - href: overview.qmd
        text: Overview
      - href: poster.qmd
        text: Poster
    right:
      - href: index.qmd
        text: Home

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual

