project:
  type: website

website:
  title: "GISProject"
  navbar:
    left: 
      - href: intro.qmd
        text: introduction
      - href: method.qmd
        text: methodology
      - href: results.qmd
        text: results
    right:
      - href: index.qmd
        text: Home
      - about.qmd
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

