project:
  type: website

website:
  title: "GISProject"
  navbar:
    left: 
      - href: index.qmd
        text: Home
      - href: overview.qmd
        text: Overview
      - href: poster.qmd
        text: Poster
      - href: report.qmd
        text: GIS Report
    right:
      - href: about.qmd
        text: About

format:
  html:
    theme: cosmos
    css: styles.css
    toc: true

editor: visual

