---
title: "G1T4: Travel So Long for What!"
editor: visual
---

This project is done under the module SMT201 Geographic Information Systems for Urban Planning by Professor Kam Tin Seong in Singapore Management University (SMU).

### Introduction

There has been a decrease in birth rates in Singapore, hence leading to fewer numbers of enrollments for schools. In 2019, MOE conducted a [merging exercise](https://www.moe.gov.sg/news/press-releases/20171229-names-of-primary-and-secondary-schools-merging-in-2019), where 7 pairs of primary schools and 3 pairs of secondary schools merged.

These were some factors that were considered for the merger of schools:

-   Schools' history and heritage

-   enrollments

-   stakeholders' interests

-   sentiments of all schools involved

In this project, we will be focusing on the Primary Schools that have been merged in 2019.

Here are some information that we found interesting!

### Information on Primary School Merger and Priority Calculations

------------------------------------------------------------------------

[Address used for Registration](https://www.moe.gov.sg/primary/p1-registration/home-address)

[Home School Distance calculation change](https://www.moe.gov.sg/primary/p1-registration/changes-to-p1-registration/what-the-change-in-home-school-distance-calculation-means-for-you)

[Names of Primary and Secondary Schools Merging Between 2022 and 2025](https://www.moe.gov.sg/news/press-releases/20220406-names-of-primary-and-secondary-schools-merging-between-2022-and-2025)

### Information on Upcoming Merger

------------------------------------------------------------------------

[8 primary and 10 secondary schools to merge](https://www.straitstimes.com/singapore/parenting-education/8-primary-and-10-secondary-schools-to-merge-over-next-three-years-amid-falling-birth-rates)

[18 primary and secondary schools to undergo mergers](https://www.channelnewsasia.com/singapore/moe-schools-merging-new-town-tanglin-telok-kurau-201401)

### 
